import { Link } from "react-router-dom"

const commandRows = [
  ["ls, cd, pwd", "Inspect the virtual workspace and move between browser-side folders."],
  ["mkdir, rm", "Create or remove files and folders in the current browser workspace."],
  ["cp, mv", "Copy or rename workspace files and folders without leaving the IDE."],
  ["cat, echo", "Read a text file or print a short value in the terminal."],
  ["grep, find", "Search text content in a file or search paths throughout the workspace."],
  ["preview, run", "Open an HTML preview or execute a selected supported file."],
]

export default function Guide() {
  return <main className="min-h-screen bg-editor-bg px-4 py-6 text-sm leading-7 text-foreground sm:px-6 lg:px-10">
    <article className="mx-auto max-w-4xl">
      <Link to="/" className="text-primary underline underline-offset-4">Back to SK Coder</Link>
      <header className="mt-6 border-b border-border pb-6"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-primary">Phase 1 user guide</p><h1 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Build, run, and keep control of your workspace</h1><p className="mt-3 max-w-3xl text-muted-foreground">SK Coder is a mobile-first web IDE for working with project folders from a browser. Phase 1 focuses on local-first editing, browser-side workspace operations, HTML preview, Python, Node.js, Bash, optional cloud execution, and GitHub-connected source control.</p></header>
      <section className="mt-8 space-y-4"><h2 className="text-2xl font-semibold">Start a workspace</h2><p>Open SK Coder and the Explorer appears beside the editor on desktop, while the Files button exposes it on smaller screens. You can create files or folders from the Explorer controls, or select <strong>Open</strong> in the top bar to import individual files, folders, or a ZIP archive. When an existing workspace is open, SK Coder asks whether you want to <strong>Replace</strong> it or <strong>Merge</strong> incoming paths. Replace clears the active file tree; Merge preserves existing entries and replaces only matching imported paths.</p><p>Imported text files remain editable. Binary project assets, including common images, are kept as binary data rather than silently converted into text. This matters when you preview a static site: relative image references can be inlined into the browser preview so that the page remains usable without a public server.</p></section>
      <section className="mt-8 space-y-4"><h2 className="text-2xl font-semibold">Edit and preview</h2><p>Select a file in Explorer to open it in a tab. The editor tracks unsaved changes, provides diagnostics through the Problems control, and respects the editor choices in Settings. HTML files use the Run button to open the built-in preview. JavaScript, CSS, and imported assets can be referenced from an HTML entry point. The preview is intended for local browser validation; it is not a substitute for a production deployment or a full development server.</p><p>Use the Preview navigation item to revisit the most recent result. If an iframe preview reports a runtime error, the error is surfaced in the Problems area so you can return to the relevant source. For React-style source files, SK Coder provides an in-browser transform preview for simple client-side work. Package-based applications, long-running servers, and project scripts require the configured Oracle backend or another real runtime.</p></section>
      <section className="mt-8 space-y-4"><h2 className="text-2xl font-semibold">Use the local terminal</h2><p>The Local terminal provides a virtual filesystem connected directly to Explorer. It is available even when the Oracle backend is unavailable. The default terminal choices in Phase 1 are Shell, Python, Node, and Bash. You may add extra sessions for your own work; only sessions you add show a close control. The default sessions stay available.</p><div className="overflow-x-auto rounded-lg border border-border"><table className="min-w-full text-left text-xs"><thead className="bg-card text-muted-foreground"><tr><th className="px-3 py-2 font-medium">Command</th><th className="px-3 py-2 font-medium">What it does offline</th></tr></thead><tbody>{commandRows.map(([command, description]) => <tr key={command} className="border-t border-border"><td className="whitespace-nowrap px-3 py-2 font-mono text-primary">{command}</td><td className="px-3 py-2 text-muted-foreground">{description}</td></tr>)}</tbody></table></div><p>Commands operate on the active workspace only. For example, <code className="rounded bg-secondary px-1.5 py-0.5">mkdir notes</code>, <code className="rounded bg-secondary px-1.5 py-0.5">cd notes</code>, and <code className="rounded bg-secondary px-1.5 py-0.5">pwd</code> create and enter <code>/notes</code>. Use <code className="rounded bg-secondary px-1.5 py-0.5">cp ../app.js .</code> to copy a file into the current directory, then use <code className="rounded bg-secondary px-1.5 py-0.5">mv app.js demo.js</code> to rename it. Commands do not have access to your computer’s real filesystem, operating-system shell, or installed browser extensions.</p></section>
      <section className="mt-8 space-y-4"><h2 className="text-2xl font-semibold">Run Phase 1 languages</h2><p><strong>Python</strong> runs in the browser through Pyodide where possible, so a normal Python file can keep working when the backend is down. <strong>Node.js</strong> uses Wandbox as its primary execution route for standalone JavaScript and falls back to the browser for compatible standalone scripts when Wandbox is unavailable. <strong>Bash</strong> supports workspace commands locally and uses the configured cloud Bash runner for single-script execution. The terminal makes execution status visible rather than pretending that a remote job ran successfully.</p><p>C/C++, Java, Go, Rust, PHP, and other compiled-language workflows are intentionally deferred from the Phase 1 interface. If you open one of those files, SK Coder explains that its runner is planned for Phase 2 instead of routing the request to a misleading terminal tab. For package managers, dev servers, containers, or heavyweight dependencies, use the Oracle Terminal or a connected Codespace after you have configured the service.</p></section>
      <section className="mt-8 space-y-4"><h2 className="text-2xl font-semibold">Keep work available and understand cleanup</h2><p>SK Coder saves the active workspace into IndexedDB in your browser. This is the primary local restore path, so refreshes and temporary connectivity failures do not normally remove your open files. Browser storage can still be cleared by you, your browser profile, private browsing rules, device management, or storage eviction. Export important projects regularly and keep a copy in version control.</p><p>If you configure an Oracle backend, SK Coder can attempt to store a temporary workspace snapshot after it has already saved locally. Temporary server snapshots are retained for <strong>up to 72 hours</strong>. The default server storage design reserves a 140 GB capacity target and switches new snapshot storage back to IndexedDB when the server reaches its 100 GB offload threshold. This temporary workspace storage is not archival backup storage. Do not rely on it for long-term retention, and do not treat it as a replacement for a private repository or your own backup process.</p></section>
      <section className="mt-8 space-y-4"><h2 className="text-2xl font-semibold">Connect GitHub and Codespaces</h2><p>Open <strong>Git</strong> from the bottom navigation to stage workspace files. Enter a repository in <code className="rounded bg-secondary px-1.5 py-0.5">owner/repository</code> form and a branch. GitHub authentication uses the existing device flow in Cloud Shell. Tokens are held in the browser for the requested GitHub actions. The Git panel lets you stage files, set a commit message, commit and push staged files, or pull the selected branch into the current workspace. Pull replaces the active workspace with the selected remote tree, so export or push local work first if you need it.</p><p>Cloud Shell lists available Codespaces and can start one. Once a Codespace is ready, SK Coder keeps the state in the panel and shows a connection URL that you can copy or follow deliberately. SK Coder does not automatically open a Codespaces terminal in a new tab. GitHub may still require its own separate authentication or service page during a user-initiated device authorization flow.</p></section>
      <section className="mt-8 space-y-4"><h2 className="text-2xl font-semibold">Use AI features deliberately</h2><p>AI assistance is optional. Add a compatible API endpoint, model, and your own key in Settings only if you choose to use it. Your key is kept in browser storage and is sent to the endpoint you configure when you request an AI operation. Before using any provider, review its terms, privacy policy, data-retention controls, and regional availability. Avoid sending secrets, customer data, private keys, or source code you are not authorized to disclose.</p><p>SK Coder does not require a login account for Phase 1. It does not create a cloud identity merely because you import a project or edit a file. The services you independently connect—such as GitHub, an AI provider, a configured backend, Wandbox, or a cloud runner—may have separate accounts and policies.</p></section>
      <section className="mt-8 space-y-3"><h2 className="text-2xl font-semibold">Quick troubleshooting</h2><details className="rounded-lg border border-border bg-card/40 p-3"><summary className="cursor-pointer font-medium">My workspace is missing after a refresh</summary><p className="mt-2 text-muted-foreground">Confirm that the browser is not in a private session and has not cleared site storage. Import the exported ZIP or pull the project from GitHub. Browser-local persistence is helpful, but it is not an infallible backup.</p></details><details className="rounded-lg border border-border bg-card/40 p-3"><summary className="cursor-pointer font-medium">A Node or Bash execution route is unavailable</summary><p className="mt-2 text-muted-foreground">Use a compatible browser fallback where presented, retry later, or configure the Oracle backend for workloads that need a real runtime. Standalone files and full package-based projects have different execution requirements.</p></details><details className="rounded-lg border border-border bg-card/40 p-3"><summary className="cursor-pointer font-medium">I need to protect a project</summary><p className="mt-2 text-muted-foreground">Export the project, push it to a private repository, and avoid storing secrets in source files. Delete temporary workspace data from the browser when using a shared device.</p></details></section>
      <footer className="mt-10 border-t border-border pt-5 text-xs text-muted-foreground">Read the <Link to="/privacy" className="text-primary underline">Privacy Policy</Link> and <Link to="/terms" className="text-primary underline">Terms of Service</Link> before using remote services. This guide describes the Phase 1 product behavior and may change as new execution features are introduced.</footer>
    </article>
  </main>
}
